### PR TITLE
Set up tox

### PR DESCRIPTION
**Pull request by csomh**
This is a the first step to configure travis-ci to check PRs. 

By using [tox](https://tox.readthedocs.io/en/latest/index.html) we can make sure that travis-ci and developers run tests the same way, and helps avoiding the _works on my machine_ dilemma.

This PR also enables measuring code coverage, sets up code linting, and fixes the issues discovered by flake8.

Might be easier to review commit-by-commit.

### CODE REVIEW

**Comment by MartinBasti** [comment]
Needs rebase

**Comment by MartinBasti** [comment]
@kevinrizza Linter rules about formatting are python PEP8 standard.
Contributors have to only run `tox` command for running tests and linting

**Comment by csomh** [comment]
Rebased.

@kevinrizza, yep, all these changes were b/c of the linter. I'll add a note to the contribution guide, too. It's better to be explicit.

**Comment by csomh** [comment]
Contribution guide updated, please check.

**Comment by kevinrizza** [comment]
Thanks for updating the contribution doc!

/lgtm

**Pull request merged**
