### PR TITLE
Set up Travis CI and Coveralls

### PR DESCRIPTION
**Pull request by csomh**
Configuration for Travis CI: run tox and push results to Coveralls, in order to have updates about coverage, too, in PR checks.

### CODE REVIEW

**Comment by MartinBasti** [comment]
@kevinrizza could you plese enable travis-ci.org and coveralls for operators courier?

**Comment by kevinrizza** [comment]
@MartinBasti I do not actually have the right privileges to do so. @aravindhp  ?

**Comment by aravindhp** [comment]
I have enabled travis-ci.org for the repository. For coveralls it seems like I need an OK from an operator-framework org admin. I have requested for approval.

**Comment by aravindhp** [comment]
Coveralls has been enabled too. LMK if I need to do anything else.

**Comment by csomh** [comment]
Thanks @aravindhp! :tada: 

I've rebased and force-pushed the branch to see them working.

**Pull request merged**
