### PR TITLE
Add logging level and module name to logs

### PR DESCRIPTION
**Pull request by awgreene**
Addresses issue #15

### CODE REVIEW

**Comment by awgreene** [comment]
Example: `csv metadata.annotations.categories not defined` -> now prints as `WARNING:operatorcourier.validate:csv metadata.annotations.categories not defined`

**Comment by scoheb** [comment]
@kevinrizza is this part of 1.0.1?

**Comment by kevinrizza** [comment]
@scoheb It is not, 1.0.1 was released before this was merged.

**Pull request merged**
