### PR TITLE
[docs] Add historical info and scripts

### PR DESCRIPTION
**Pull request by aravindhp**
Add historical documentation and scripts about how pushes to quay worked before operator-courier.

Source: https://github.com/operator-framework/operator-marketplace/blob/01191f30a98ad77550505bacb631a5171b5d68f8/docs/how-to-upload-artifact.md

### CODE REVIEW

**Comment by aravindhp** [comment]
@awgreene please review, so that it can be merged.

**Comment by aravindhp** [comment]
What needs to be done to merge this?

**Comment by kevinrizza** [comment]
> What needs to be done to merge this?

Alex's lgtm. Merging now.

**Pull request merged**
