### PR TITLE
Use argparse subparsers for subcommands

### LINKED ISSUE #77: document --ui_validate_io switch
--ui_validate_io was asked to be used to verify data for operatorhub.io, but it isn't documented in readme or in the --help output.

### PR DESCRIPTION
**Pull request by csomh**
Makes argument parsing more resilient, by handling
subcommands with argparse provided and recommended [subparsers][1],
instead of the current custom manipulation of argv.

Removes the need to manually update and format the top-level
help message: this is going to be composed from the help strings
of the subcommands by argparse.

Fixes the issue of subcommand's usage string not displaying the
subcommand.

Removes the need to explicitly check for incorrect subcommands.

Enables extending the CLI with top-level optional arguments, without the
need of adjusting argv parsing.

[1]: https://docs.python.org/3/library/argparse.html#sub-commands

### CODE REVIEW

**Comment by kevinrizza** [comment]
What is the advantage of using `subcommand` versus the current implementation?

Also, https://github.com/operator-framework/operator-courier/issues/77 should be solved by a separate pr. Please do not co-mingle multiple changes in a single pull request.

**Comment by csomh** [comment]
[Subparsers][1] are the argparse provided way to handle subcommands. Switching to this was easier than figuring out the bug in the custom implementation, which was causing #77 or led to an incorrect usage text to be displayed for subcommands.

Sorry, the commit message didn't clarify this. Updated it, together with the initial PR comment.

[1]: https://docs.python.org/3/library/argparse.html#sub-commands

**Comment by kevinrizza** [comment]
How do you know that there was a bug at all? It seems like the command has description output, and I'm not sure that your change fixed any bug at all. It seems more likely to me that the issue in question was describing a perceived lack of documentation about what the flag outputs (aside from the very basic description of the flag).

That could be a separate discussion, but I don't think this PR fixes the issue.

And, again, I still don't see what using `subcommand`s contributes here. Is there some design limitation to the current implementation (aside from not using some specific sub library)? What does moving to using `subcommand` actually give us that we don't have already? If there is a technical argument to be made for them, I am certainly interested in hearing it.

**Comment by csomh** [comment]
Oh, ok, I see now. You're right.

**Comment by MartinBasti** [comment]
This PR is still valid (but must be updated), There were already several issues caused by not using subparsers.

* https://github.com/operator-framework/operator-courier/pull/85
* https://github.com/operator-framework/operator-courier/pull/89
* https://github.com/operator-framework/operator-courier/issues/88

**Comment by csomh** [comment]
Updated.

**Comment by MartinBasti** [comment]
works for me

**Pull request merged**
