### PR TITLE
Clean up additional folders generated by tox

### PR DESCRIPTION
**Pull request by jeremylinlin**
/cc @kevinrizza @awgreene

### CODE REVIEW

**Comment by csomh** [comment]
Based on the docs, `make` is used for builds and deployments. `tox` is used for texting? Why does `make clean` need to touch `tox` artifacts?

**Comment by kevinrizza** [comment]
@csomh Running tests is a necessary part of determining if a build should run successfully. I do not see a problem with using `make` to clean up any artifacts left over from running any temporary workflow that is associated with building or releasing from a repository. `make clean` is a common pattern in dev workflows, as is `make unit` or `make test`

**Comment by csomh** [comment]
@kevinrizza, ok, I see now. Thanks!

**Pull request merged**
