### PR TITLE
Move logging.basicConfig() from api to cli

### LINKED ISSUE #58: Broken logging
Operator-courier breaks my logging

expected output:
```
FLASK_APP=omps/app.py flask run
 * Serving Flask app "omps/app.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
2019-03-12T09:20:36Z - [9548] werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-03-12T09:20:40Z - [9548] werkzeug - INFO - 127.0.0.1 - - [12/Mar/2019 10:20:40] "GET /v1/health/ping HTTP/1.1" 200 -
2019-03-12T09:20:45Z - [9548] werkzeug - INFO - 127.0.0.1 - - [12/Mar/2019 10:20:45] "GET /v1/health/ping HTTP/1.1" 200 -
```

output after upgrading from 1.0.0 to 1.2.0
```
FLASK_APP=omps/app.py flask run
 * Serving Flask app "omps/app.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
WARNING:operatorcourier.validate:csv metadata.annotations not defined.
WARNING:operatorcourier.validate:csv spec.icon not defined
WARNING:operatorcourier.validate:csv metadata.annotations not defined.
WARNING:operatorcourier.validate:csv spec.icon not defined
ERROR:omps.quay:Publishing repository: Unknown error
```

* I'm not able to enable DEBUG loglevel
* log_format changed to from expected format to operator-courier format

It is caused by this: `operatorcourier/api.py:logging.basicConfig()` added by this commit 9137d58df325e107bdc127c862ddaf0ec2928299

Please fix this issue as logging configuration should not never happen in module only in main/cli (repeated myself here)

### PR DESCRIPTION
**Pull request by awgreene**
Logging should be set in the cli rather than the api to
avoid overwritting logging settings set by the user.

Fixes #58

### CODE REVIEW

**Comment by kevinrizza** [comment]
@awgreene can you specify in the pr description and the commit message why you are making this change?

**Comment by awgreene** [comment]
@kevinrizza addressed.

**Comment by MartinBasti** [comment]
/lgmt

coverage decrease is just common fluctuation as we moved lines to another file

**Pull request merged**
